#ifndef BEDROOM_LED_CONTROLLER_SECRETS_EXAMPLE_H
#define BEDROOM_LED_CONTROLLER_SECRETS_EXAMPLE_H

#define BEDROOM_WIFI_SSID "YOUR_WIFI_NAME"
#define BEDROOM_WIFI_PASS "YOUR_WIFI_PASSWORD"
#define BEDROOM_OTA_USER "admin"
#define BEDROOM_OTA_PASS "CHANGE_ME_OTA_PASSWORD"
#define BEDROOM_FALLBACK_AP_PASS "bedroomleds"

#endif
